### ISSUE TITLE
A few questions on specific usage of OAuthSwift

### ISSUE THREAD

**Issue by damianesteban** [dongri/OAuthSwift#100]
I have OAuth all setup and working fine for my application's authorization but I have a few questions that I'm hoping someone can answer:

1.)  Does OAuthSwift provide a way to store the token in the keychain?  Does it do so by default?

2.)  The authorization examples are great, but is there a basic example that shows how to make a GET request with the access token?

Thank you.

**Comment by phimage** [comment]
1/ no keychain store, but there is encoding and decoding method into OAuthSwiftCredential
So you can archive into nsdata and store in keychain

I make a framework for preferences and there is keychain storing
https://github.com/phimage/Prephirences/

```swift
let keychain = KeychainPreferences.sharedInstance
keychain.setObjectToArchive(theCredential, "a string key")

if let retrievedCredential = keychain.unarchiveObjectForKey("the same key") {.. }
```

2/ look into demo app
there is some get request with automatic use of credential in http header
```swift
oauthswift.client.get(...
```
but you can do it manually , see code like #99

**Comment by damianesteban** [comment]
Thanks a lot, this helped tremendously.
