### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by gabriel-jones** [dongri/OAuthSwift#101]
The library should be extended to work with Reconnect APIs (revalidating OAuth tokens). See Intuit Reconnect API <a href ="https://developer.intuit.com/docs/0050_quickbooks_api/0020_authentication_and_authorization/oauth_management_api#/Reconnect" target="_blank"> here </a>.

**Comment by phimage** [comment]
did you see other api provide the same protocol to reconnect? with similar error code
or there is a RFC?

if not, this is a specific "extension", not to integrate by default in the OAuthSwift framework (could be an other project)

there is also Disconnect

**Comment by phimage** [comment]
After reading the Inuit doc, this not generic and will not be implemented as a generic feature
XML parsing is necessary

You must do a get request on url described in doc
Get the xml, parse it with some swifty xml library
Check if error, and of not get token and token secret and do

```swift
oauth.client.credential.oauth_token = { token from xml}
oauth.client.credential.oauth_token_secret = {secret token from xml}
```
