### ISSUE TITLE
OAuth2 - client_id != consumer_key ... 

### ISSUE THREAD

**Issue by peteclark3** [dongri/OAuthSwift#104]
It seems like your oauth2 code doesn't distinguish between the consumer_key and the client_id.  I am trying to use it against Fitbit's oauth2 implementation and because your code treats them as one and the same, I either get an "invalid client_id" error or an "invalid consumer_key" error.  

Any plans to distinguish between the two?

**Comment by phimage** [comment]
For OAuth version 2 only `client_id` is used by this framework event if the variable is named consumer_key (also named client consumer key, client key sometimes)
see
```swift
"client_id=\(self.consumer_key)"
 parameters["client_id"] = self.consumer_key
```
So if you use OAuth version 2 , use the "Oauth2 client id" into `consumerKey`attribute

Only for OAuth version 1, consumer_key is used with this name for authentification header
```swift
authorizationParameters["oauth_consumer_key"] = self.consumer_key
```

The name is the same just to factorize code between the two class
