### ISSUE TITLE
Can't set up framework

### ISSUE THREAD

**Issue by tomasscavnicky** [dongri/OAuthSwift#117]
I've been struggling with adding OAuthSwift framework to my project. I've tried all possible methods(Cocoapods, DragNDrop + Build Phase dependencies, Carthage), but in each case I'm getting following error on import OAuthSwift line: No such module 'OAuthSwift'. Any ideas what to do?

**Comment by phimage** [comment]
with Cocoapods, did you open the xcode "workspace" generated, not your xcode project

**Comment by tomasscavnicky** [comment]
the issue was that i had swift 1.2 installed

**Comment by phimage** [comment]
so with the current master branch is doesn't compile (always possible to choose old git tag with cocoadpod, but no more bug fix in swift 1.2)

@tomasscavnicky please close the issue
