### ISSUE TITLE
App Store issue - Safari

### ISSUE THREAD

**Issue by nabil-takla** [dongri/OAuthSwift#118]
My app was rejected by the App Store for the following reason: Upon launching the app, a web page in mobile Safari opens for logging in LinkedIn, then returns the user to the app. The user should be able to log in without opening Safari first. Any suggestions?

**Comment by phimage** [comment]
see demo and `oauthswift.authorize_url_handler =  ...` to not open external safari

**Comment by nabil-takla** [comment]
Thanks! Which file is this in?

**Comment by phimage** [comment]
you can search in github in the current depository
https://github.com/dongri/OAuthSwift/search?utf8=%E2%9C%93&q=oauthswift.authorize_url_handler+%3D

You will see
`oauthswift.authorize_url_handler = WebViewController()`

`WebViewController` is a class that you implement with an `UIWebView` or `WKWebView `
The example use `UIWebView`

P.S. Please close this issue when you have found the solution
