### ISSUE TITLE
Credential User ID and Refresh Token has been removed

### ISSUE THREAD

**Issue by jwrigh26** [dongri/OAuthSwift#122]
Comparing to an older version, within class OAuthSwiftCredential the two public vars user_id and refresh_token have been removed. Did some testing and when you go to step #3 on OAuth1Swift.swift, the user_id parameter is still being returned but you are no longer adding the credential of the client.

Plus there is no way to get this back ourselves without altering the library because you only pass the response back into the closure.

Adding this back would be awesome!

**Comment by phimage** [comment]
I don't know anything about old release, could you specify the "older version" tag
to see `user_id` into `OAuthSwiftCredential`

**Comment by jwrigh26** [comment]
So the story goes the developers that were working on a co-project included the library as a framework. I can show a screen shot of the variables. I'm now wondering if they edited your work without documenting anywhere there changes. Do you know if you ever included these two variables in OAuthSwiftCredential?

user_id
refresh_token
 
![screen shot 2015-10-07 at 10 34 41 am](https://cloud.githubusercontent.com/assets/8534039/10340649/2b590750-6cdf-11e5-8dd4-b6ca0e1ce1a6.png)

**Comment by jwrigh26** [comment]
I apologize. I went looking at all previous versions and those two variables were never used. I do like the use of those two variables. But I believe it should have been properly forked and then submitted back to you to decide if you wanted to add this to your library.

I will close this issue. Sorry for wasting your time.
