### ISSUE TITLE
Need help understanding how to use with existing auth_token/auth_token_secret

### ISSUE THREAD

**Issue by pbeaumier** [dongri/OAuthSwift#126]
Hi, I really need help understanding how to use the library. I can run the example and it's working great but once I use the authorizeWithCallBackURL and get my auth_token and oauth_token_secret, I have no clue how to re-use those to make a GET/POST when re-running the app without having to go through authentication authorization again. 

I have auth_token = "my_auth_token" and my auth_token_secret = "my_auth_token_secret" and of course consumer key and secret.

I am trying to get timeline from my Twitter account. How do I use the already obtained token to get access without requesting new token? I would really appreciate if somebody could post an example. Thanks

**Comment by phimage** [comment]
You get it, so you can also set it at start

**Comment by phimage** [comment]
```swift

 let oauth = OAuth1Swift ( // or OAuth2Swift
...
 )

oauth.client.credential.oauth_token =  mytoken
oauth.client.credential.oauth_token_secret = mytoken_secret
oauth.client.credential.oauth_header_type = "oauth1" or "oauth2" // just a fix because not initialized at init yet

```
