### ISSUE TITLE
OAuthSwift does not work within a widget

### ISSUE THREAD

**Issue by DennisDreissen** [dongri/OAuthSwift#129]
*/Pods/OAuthSwift/OAuthSwift/OAuthSwiftURLHandlerType.swift:33:31: 'sharedApplication()' is unavailable: Use view controller based solutions where appropriate instead.

**Comment by phimage** [comment]
OAuthSwiftURLHandlerType is a protocol that you can implement

OAuthSwiftOpenURLExternally is just the default one, and simply use application method to open externally the URL

To allow compilation I don't think there is an other way than add "#if/#else/#endif" preprocessor macros to exclude code in widget
where

**Comment by phimage** [comment]
PR #143 add OAUTH_APP_EXTENSIONS var to disable code `UIApplication. sharedApplication`

With cocoapod post install setting must be add into podfile for extension target
https://guides.cocoapods.org/syntax/podfile.html#post_install

**Comment by phimage** [comment]
wiki page added, PR merge is next
https://github.com/dongri/OAuthSwift/wiki/Work-with-application-extension
