### ISSUE TITLE
Example of one API call for each service

### ISSUE THREAD

**Issue by sumitk1** [dongri/OAuthSwift#13]
Hey @dongri. Awesome job making this example!
Can you include an example of one api call for each service? 
e.g.

```
oauthswift.client.get("http://api.linkedin.com/v1/people/~?", parameters: parameters, success: { (data, response) -> Void in
            println("Succes") // or print some data from the profile
            }, failure: { (error) -> Void in
                println("Failed") // or reason what failed
        })
```
When I do the above for linkedIn I am getting Failure in the following function:

```
    func doOAuthLinkedin(){
        let oauthswift = OAuth1Swift(
            consumerKey:    Linkedin["consumerKey"]!,
            consumerSecret: Linkedin["consumerSecret"]!,
            requestTokenUrl: "https://api.linkedin.com/uas/oauth/requestToken",
            authorizeUrl:    "https://api.linkedin.com/uas/oauth/authenticate",
            accessTokenUrl:  "https://api.linkedin.com/uas/oauth/accessToken"
        )
        oauthswift.authorizeWithCallbackURL( NSURL(string: "oauth-swift://oauth-callback/linkedin")!, success: {
            credential, response in
            print("\n client oauth_token - " + credential.oauth_token)
            print("\n client oauth_token_secret - " + credential.oauth_token_secret)
            print("\n client consumer_key - " + credential.consumer_key)
            print("\n client consumer_secret - " + credential.consumer_secret)
            print("\n client oauth_verifier - " + credential.oauth_verifier)
            
        var parameters =  Dictionary<String, AnyObject>()
        parameters["oauth_nonce"] = "1234"
        oauthswift.client.get("http://api.linkedin.com/v1/people/~?", parameters: parameters, success: { (data, response) -> Void in
            println("Success")
            }, failure: { (error) -> Void in
                println("Failed")
        })
        self.performSegueWithIdentifier("jumpToUserTable", sender: self)
        
    }
```

**Comment by sumitk1** [comment]
Hi @dongri this worked like a charm. Thanks for the help! I am using NSXMLParser for this as well.

**Comment by realin** [comment]
Hello @dongri 
Can you guide me here, what i am doing wrong here.

`let oauthswift = OAuth1Swift(
            consumerKey:    "myKeyHere",
            consumerSecret: "mySecretHere",
            requestTokenUrl: "http://sitename/wc-api/v2/products",
            authorizeUrl:    "http://sitename/wc-api/v2/products",
            accessTokenUrl:  "http://sitename/wc-api/v2/products"
        )
        //oauthswift.authorize_url_handler = get_url_handler()
        oauthswift.authorizeWithCallbackURL( NSURL(string: "sitename/wc-api/v2/products")!, success: {
            credential, response, parameters in
            //            self.showTokenAlert(serviceParameters["name"], credential: credential)
            self.testOauth(oauthswift)
            }, failure: { error in
                print(error.localizedDescription)
            }
        )
   

    func testOauth(oauthswift: OAuth1Swift) {
        oauthswift.client.get("http://sitename/wc-api/v2/products", parameters: [:],
            success: {
                data, response in
                let jsonDict: AnyObject! = try? NSJSONSerialization.JSONObjectWithData(data, options: [])
                
                print("jsonDict: \(jsonDict)")
                
            }, failure: { error in
                print(error)
        })
    }`

I cannot get the data in jsonDict.  It gives me this error:
HTTP Status 404: Not Found, Response: 

{"errors":[{"code":"woocommerce_api_authentication_error","message":"oauth_consumer_key parameter is missing"}]}


Can you help me here.
Thanks

**Comment by phimage** [comment]
Your callback URL into authorizeWithCallbackURL is wrong and others also in init...

Why removing issue template ? And do not respond to the question? (Os, provider, version)

**Comment by phimage** [comment]
Look into woocommerce oauth API to find the good urls

**Comment by realin** [comment]
@phimage Can you guide me here, what should be the correct code?

**Comment by phimage** [comment]
Did you read my message, go to oauth Doc of woocommerce... I can help but not work for you, try by yourself...
