### ISSUE TITLE
Logout process

### ISSUE THREAD

**Issue by lokatorius** [dongri/OAuthSwift#130]
Hello,

I was trying to make logout functionality with oauthswift. But I was not able to figure out how to do it. 
Now it is connecting automatically every time. How to switch users?

Thank you for your help.

**Comment by phimage** [comment]
did you use a webview? sometimes cookies must be deleted to change user

then you could recreate an OAuthSwift object
or edit credential : reset oauth_token, oauth_token_secret and maybe other things

depending on the used api, you could revoke the token before doing that

**Comment by lokatorius** [comment]
Thank you for the answer it solved the issue.

**Comment by sourov2008** [comment]
Hey I am using webview and trying to make logout functionality with oauthswift 
After first login web view appear as a blank and immediately open an alert box for confirming open the app .

I have a Disconnect/Logout button in my apps . When user tap the button I tried to delete the cookies 

```
        NSURLCache.sharedURLCache().removeAllCachedResponses()
        if let cookies = NSHTTPCookieStorage.sharedHTTPCookieStorage().cookies {
            for cookie in cookies {
                NSHTTPCookieStorage.sharedHTTPCookieStorage().deleteCookie(cookie)
            }
        }
```

But not working .
I have tried to reset oauth_token, oauth_token_secret .
but nothing work properly .

**Comment by phimage** [comment]
There is two type of webview, say the class name...

**Comment by sourov2008** [comment]
Still now I am using OAuthSwiftDemo
and it seems using WebViewController.swift class ->UIViewController->UIWebView

**Comment by phimage** [comment]
try also reset cache

and after deleting cookies, do a NSUserDefaults standardUserDefaults synchronize 'i read on stackoverflow

**Comment by Rushabh5** [comment]
@lokatorius  How did you achieve this? Can you please share your code here for logout process?
