### ISSUE TITLE
Please tell me I'm totally missing something…

### ISSUE THREAD

**Issue by ts** [dongri/OAuthSwift#131]
New to Swift, and for all intents and purposes, iOS and Cocoa in general. That said, what is going on in `OAuthSwifttClient.get` that I don't seem to understand? It returns `NSData` and I can't for the life of me parse anything useful out of it.

My simple test is as follows:

````
        oauthswift.client.get("https://www.strava.com/api/v3/athlete/activities", parameters: ["per_page":10], success: {
            data, response in
            
                do {
                    print(data)
                    if let jsonResult = try NSJSONSerialization.JSONObjectWithData(data, options: []) as? NSDictionary {
                        print("jsonResult: \(jsonResult)")
                    }
                } catch {
                    print("error: \(error)")
                }
            }, failure: {
                error in
                    print("error: \(error)")
        })
````

To which I get the raw `NSData` as expected, but without anything following.

I'm sure I just don't understand Swift/Cocoa/Xcode or something because this is extremely simple stuff and there is no way it should be this difficult to work with.

**Comment by phimage** [comment]
Just to debug try convert the NSData to String or NString

You cast as NSDico.. add an else {...} or remove the cast

**Comment by ts** [comment]
Sounds like the right thing to do, but again, I'm kneecapped by Swift and the new territory I found myself in. When I do `print(String(data))` I get exactly the same result, which isn't readable or usable (hence trying to serialize it in the first place…) so I'm not sure what to do now.

**Comment by phimage** [comment]
Look for NSData to NString, encoding must ne specified in init
