### ISSUE TITLE
What's about Magento Rest API?

### ISSUE THREAD

**Issue by csnu17** [dongri/OAuthSwift#134]
I had changed some parameters and url endpoint for matching with Magento Rest API. Unfortunately, when I granted and callback from webview to my app again the response always said
"Error Domain=oauthswift.error Code=-1 "Oauth problem." UserInfo={NSLocalizedFailureReason=Oauth problem.}"

Thank you for your help.

**Comment by phimage** [comment]
did you set  `oauth.allowMissingOauthVerifier=true`
you must do that when the api don't return the security parameter `oauth_verifier`

the other reason could be that the returned parameter by api is not named  `oauth_token` or `token`

ps: If this work please close the issue

**Comment by csnu17** [comment]
I have resolved it. The error was happened because when it was callback from Magento to my app, I forgot to append query string from Magento with my scheme before callback. However, thank you for your answer. :)
