### ISSUE TITLE
Bug when extracting the parameters from the query string 

### ISSUE THREAD

**Issue by mohwaili** [dongri/OAuthSwift#145]
Ampersand in the parameters dictionary after authenticating. Off course the authentication will always fail.

![bug](https://cloud.githubusercontent.com/assets/9988884/11068121/33a00f92-87d0-11e5-8516-d0958ac08805.png)

**Comment by phimage** [comment]
I think callback url is malformed : ..avans?&oauth... must be ..avans?oauth...
Maybe url RFC allow it, but I think it's bad
So I think nothing will be done into OAuthSwift code to support that

I think the workaround is change your callback url by adding a parameter
..avans?dummy=1
and maybe the website will return a callback url like that ..avans?dummy=1&oauth...

**Comment by mohwaili** [comment]
I've no control over the back-end so I can't change that.

**Comment by mohwaili** [comment]
@phimage thank you, adding the dummy=1 fixed the problem
