### ISSUE TITLE
Use of unresolved identifier 'failureHandler'

### ISSUE THREAD

**Issue by froggerdev** [dongri/OAuthSwift#146]
Beginner coder here, not sure what I've done wrong but Xcode is shouting at me from this line:

oauthswift.authorizeWithCallbackURL( NSURL(string: "http://google.com"), scope: "basic", state:"INSTAGRAM", success: {
            credential, response, parameters in
            println(credential.oauth_token)
            }, failure: failureHandler)

Error is as title states, "unresolved identifier". Obviously because failureHandler was never declared but declaring shoots out even more errors. Thanks for any advice in advance.

**Comment by phimage** [comment]
"unresolved identifier" means not defined...
I see, you copy readme code
Go to demo to have real code 
https://github.com/dongri/OAuthSwift/blob/master/OAuthSwiftDemo/ViewController.swift

```swift
oauthswift.authorizeWithCallbackURL( NSURL(string: "http://google.com"), scope: "basic", state:"INSTAGRAM", success: {
credential, response, parameters in
println(credential.oauth_token)
},  failure: {(error:NSError!) -> Void in
            print(error.localizedDescription)
})
```

`state:"INSTAGRAM" `is for instagram
you can generate string like that
```swift
        let state: String = generateStateWithLength(20) as String
```


Then http://google.com is not a valid callback url, it must be an url that you must handle by url scheme (see readme  and the scheme must be yourapplicationname://) or by implementing a webview and its delegate  - in final `OAuth2Swift.handleOpenURL(url)` must be call

**Comment by froggerdev** [comment]
You got it man. Thank you very much for your support. Much appreciated.
