### ISSUE TITLE
Changelog File

### ISSUE THREAD

**Issue by mctavishsolutions** [dongri/OAuthSwift#148]
Please add a CHANGELOG.md file to make it easier to see what's changed with each release.

**Comment by phimage** [comment]
I can't talk for @dongri for all previous releases until 0.4.6

But for the next one I make https://github.com/dongri/OAuthSwift/wiki/Roadmap to communicate about change I make or merge to @dongri

ps: altenative to changelog, when doing a release just add a description about change
https://github.com/dongri/OAuthSwift/releases

**Comment by mctavishsolutions** [comment]
One benefit of using the CHANGELOG.md over just git release tags file in the root directory is that it gets picked up by CocoaPods and is visible their and your pod is marked higher on their "quality estimate".

**Comment by phimage** [comment]
I think changelog.md will not be created, or only if automatic process exist
Not enought time to do it
