### ISSUE TITLE
Podspec Out of Date

### ISSUE THREAD

**Issue by mctavishsolutions** [dongri/OAuthSwift#149]
Currently the podspec is at Version 0.4.7, however the most recent git tag is 0.4.6 so that is the version getting pulled in by Cocoapods.

Please update the git tags and [update the Cocoapods master trunk](https://guides.cocoapods.org/making/specs-and-specs-repo.html#how-do-i-update-an-existing-pod).

**Comment by phimage** [comment]
There is no gitflow with develop branch
master branch is under development and will be 0.4.7

0.4.6 is the last stable release

If you gtake timeto read roadmap wiki page "pod trunk push", there is task about that, when I finish regression test on all changes (add test unit on signature oauth1) I will ask dongri to make a new release
