### ISSUE TITLE
Test Suite is not included

### ISSUE THREAD

**Issue by raulriera** [dongri/OAuthSwift#15]
Which resolves in "The file “Info.plist” couldn’t be opened because there is no such file."

**Comment by dongri** [comment]
https://github.com/dongri/OAuthSwift/blob/master/Example/OAuthSwiftDemo/Info.plist ?

**Comment by raulriera** [comment]
That is the Demo plist, not the tests one. Try checking out this repo and building it with Xcode 6.2 (or 6.1) there is no Test folder in this repo, yet the project has a reference to it

**Comment by dongri** [comment]
Sorry...
I removed tests from targets
https://github.com/dongri/OAuthSwift/commit/1e125827ee18f1bb8c4a9587e5c6a22ba17375b4

**Comment by raulriera** [comment]
thanks man!
