### ISSUE TITLE
HTTP Response doesn't always have an 'access_token' key.

### ISSUE THREAD

**Issue by SokichiFujita** [dongri/OAuthSwift#150]
The following error occurred in the GitHub authorization flow.

[OAuth2Swift.swift](https://github.com/dongri/OAuthSwift/blob/master/OAuthSwift/OAuth2Swift.swift)
![OAuthSwift](https://cloud.githubusercontent.com/assets/15647722/11421705/c44dae36-9479-11e5-9314-64cc66645257.png)

In regard to this response, it has only `"error_description"`, `"error"` and `"error_uri"` keys. There are no 'access_token' key. Please consider to validate whether it has `"access_token"` key or not. `if let` statement may be a solution.

**Comment by SokichiFujita** [comment]
I don't know why GitHub uses status code 200 for this response.

**Comment by phimage** [comment]
Already fixed in master branch and available in next release
as you can see in code link you put

```swift
   guard let accessToken = responseParameters["access_token"] as? String else {
                    if let failure = failure {
                        let errorInfo = [NSLocalizedFailureReasonErrorKey: NSLocalizedString("Could not get Access Token", comment: "Due to an error in the OAuth2 process, we couldn't get a valid token.")]
                        failure(error: NSError(domain: OAuthSwiftErrorDomain, code: -1, userInfo: errorInfo))
                    }
                    return
                }
```

**Comment by SokichiFujita** [comment]
Thank you! I expect the release!

**Comment by phimage** [comment]
どういたしまして
