### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by raulriera** [dongri/OAuthSwift#17]
I tried forking the repo and creating support for [Carthage](https://github.com/Carthage/Carthage) but I ran into several issues with the Crypto library, since you can't use Bridging Headers in frameworks. I found a weird way of using it as seen here http://stackoverflow.com/a/25250520/293731

**Comment by dongri** [comment]
Hi @raulriera 
I was modified to carthage support.
https://github.com/dongri/OAuthSwift/pull/18
https://github.com/dongri/OAuthSwift/blob/master/README.md#installation

**Comment by raulriera** [comment]
You rule!
