### ISSUE TITLE
No such module 'CommonCrypto' in String+OAuthSwift.swift when installed through CocoaPods

### ISSUE THREAD

**Issue by harlanhaskins** [dongri/OAuthSwift#20]
![screen shot 2015-01-20 at 10 44 02 am](https://cloud.githubusercontent.com/assets/853032/5820199/49de49a8-a091-11e4-9b1b-1371f0dee589.png)

Seems the CommonCrypto `module.map` is being ignored by CocoaPods.

**Comment by alexdibattista** [comment]
1. In Build Settings under Swift Compiler - Search Paths
2. Add the path to OAuth/CommonCrypto directory i.e /Documents/OAuthSwift-master/OAuthSwift/CommonCrypto

**Comment by 0111b** [comment]
Its better to add relative path like so : 
>${SRCROOT}/CommonCrypto

**Comment by alexdibattista** [comment]
Agreed I deleted my comment by accident

**Comment by harlanhaskins** [comment]
Wondering if there's a better way to do that automatically using CocoaPods. For now, this works. Thanks!

**Comment by bizz84** [comment]
Same problem here, tried to add in build settings either to app target or OAuthSwift Pod target but the error persists

**Comment by danieljacobarcher** [comment]
+1 Having this problem too.

**Comment by dongri** [comment]
Hi @harlanhaskins @bizz84 @danieljacobarcher 

I Removed CommonCrypto !!!!!
https://github.com/dongri/OAuthSwift/commit/5d6f60d749fe25312196c4aab7bd05973f666893
CommonCrypto setting no longer need of.
please see latest README if need...
latest version is 0.3.0

**Comment by danieljacobarcher** [comment]
Thank you!

**Comment by harlanhaskins** [comment]
This is awesome! Thank you!
