### ISSUE TITLE
Abiltiy to complete authentication without leaving the application

### ISSUE THREAD

**Issue by rjourde** [dongri/OAuthSwift#21]

**Comment by benjaminboxler** [comment]
Trying to get Authenticating in UIWebView working

+1

**Comment by dongri** [comment]
:+1:

**Comment by dongri** [comment]
Hi @rjourde @benjaminboxler 

Complete authentication without leaving the application
https://github.com/dongri/OAuthSwift/commit/8b414e4075eaa8d9fa4dc22675b2de2c3dba5da5

**Comment by dongri** [comment]
![screen shot 2015-02-12 at 22 22 00](https://cloud.githubusercontent.com/assets/878993/6168115/a773aff0-b305-11e4-8e79-dca448e76f38.png)
