### ISSUE TITLE
In app authentication - demo request

### ISSUE THREAD

**Issue by anbarasu0504** [dongri/OAuthSwift#25]
How to complete authentication, without leaving the app ? Can you please include it in the demo.

**Comment by dongri** [comment]
Hi @anbarasu0504 

You can create WebViewController as https://github.com/dongri/OAuthSwift/blob/master/OAuthSwiftDemo/WebViewController.swift

set webViewController 
https://github.com/dongri/OAuthSwift/blob/master/OAuthSwiftDemo/ViewController.swift#L38
