### ISSUE TITLE
Keep user logged

### ISSUE THREAD

**Issue by pistacchio** [dongri/OAuthSwift#26]
Hi,
suppose that I have an app with a Twitter login button. After the login, I'm given back the credentials and I can store them in NSUserDefaults.standardUserDefaults()
If the user runs the app again, and I see that he has auth credentials already set, how can I set up the oauth client so that it uses them without requiring the login again?

Also, once the user it logged in, how to get info of the logged user, such is user id etc?

Thanks

**Comment by Niels-P** [comment]
Did you already find an answer for this question? Because I am currently having the same problem. I saved the token and the secret key but now I want to verify if this information is still correct without having the user to re-authenticate again. 

Somehow we have to manually set the credential information and tokens that the applications set when a user logged in.

**Comment by Niels-P** [comment]
Okay I found out how to do it.

In the framework file OAuthClientSwift you add this function in the first class
```
    public func setUserDetails(token: String, secret: String, parameters: Dictionary<String, AnyObject>) {
        self.credential.oauth_token_secret = secret;
        self.credential.oauth_token = token;
    }
```
Then in your view controller you add:
```
oauthswift.client.setUserDetails("Here the token you saved", secret: "here the secret you saved", parameters: parameters)
        
        oauthswift.client.get("https://api.linkedin.com/v1/people/~:(skills,first-name,last-name,picture-url)", parameters: parameters,
            success: {
                data, response in
                println("PARAMETERS: \(parameters)");
                let dataString = NSString(data: data, encoding: NSUTF8StringEncoding)
                println(parameters);
                println(dataString);
            }, failure: {(error:NSError!) -> Void in
                println(error)
        })

```

That way you can use the token and secret without having to authorize all over again. Remember to check if the token is still valid by checking the LinkedIn response on failure.

**Comment by pistacchio** [comment]
Hi,
yes, I ended up doing something very similar to be able to set the credentials from outside the class. I think this should be added to the project.

**Comment by hopye** [comment]
i have the same questions, im using instagram auth . i do not know how to get the id, and other info instagram provides when authenticating... i took the code from the example...

Instagram only provides that info at authorization only looks like, then  you can use the other end points, but theres no https://api.instagram.com/v1/users/myinfo   , the /self/feed , returns the feed from the user but no logged user info..

Can someone please point me in the right direction ?


  oauthswift.authorizeWithCallbackURL( NSURL(string: "comalacartado://oauth-callback/instagram")!, scope: "likes+comments+basic", state:"INSTAGRAM", success: {
            credential, response in
            self.showAlertView("Instagram", message: "oauth_token:\(credential.oauth_token)")
            
            let url :String = "https://api.instagram.com/v1/users/self/feed/?access_token=\(credential.oauth_token)"
            let parameters :Dictionary = Dictionary<String, AnyObject>()

**Comment by phimage** [comment]
If PR #78 validated
```swift        
oauthswift.client.credential.oauth_token = "here your data"
oauthswift.client.credential.oauth_token_secret = "here your secret data"
```
