### ISSUE TITLE
Swift 1.2

### ISSUE THREAD

**Issue by danieljacobarcher** [dongri/OAuthSwift#27]
When do you expect an update to be compatible with Swift 1.2?

I get an error saying that "the module was compiled using an older version of the compiler".

I installed via Carthage.

**Comment by dongri** [comment]
Support for Swift 1.2  
https://github.com/dongri/OAuthSwift/pull/28

**Comment by khoogheem** [comment]
This probably should be a new branch as 1.2 requires Xcode 6.3beta so anyone trying to do stuff in 6.2 will cause a lot of issues..
