### ISSUE TITLE
Serious compile issues

### ISSUE THREAD

**Issue by TarangKhanna** [dongri/OAuthSwift#31]
The error is: unknown>:0: error: could not build Objective-C module 'OAuthSwift'
It works and suddenly it gives this error on build. I have tried this on 3 different laptops and the solution to clean build and delete derived data does not work all the time. Sometimes it shows one error(aforementioned) or it shows 21 errors
We spent over 4 hours with apple engineers on this in a hackathon with no progress. 
Thank you for your work!

**Comment by danshev** [comment]
I believe related:

When I open the Demo in the newest version of xCode 6.2 (6C131e), I also get a lot of compile errors.  Many are in the `OAuth1` and `OAuth2` due to the use of `as!`.  When I remove the exclamation, the errors go away, except for a few:

`Cannot downcast from 'UIViewController?' to non-@objc protocol type 'WebViewProtocol'`

on the line:

    if let webView = self.webViewController as WebViewProtocol {

**Comment by Chrisell** [comment]
Same issues here. Xcode Version 6.2 (6C131e) as well.

**Comment by ramki1979** [comment]
How to build this with 6.1.1, I am getting the following errors for length & size methods in String+OAuthSwift.swift

```swift
'String' is not convertible to 'Range<I>'
```

**Comment by gabriel-jones** [comment]
There are a few things which Dongri should change for this project, but I'll tell you guys anyway so you know what to fix. There are a few main types of errors. First, the down casting he does looks like this:
```  as! String ```
Which will make an error. What you have to do is write this:
```  as String! ```

--------------------------------------------------------------------------------------------

Next error is what danshev said: 
``` if let webView = self.webViewController as? WebViewProtocol  ```
Has an error. Easiest way to fix this is to go to ```OAuthWebViewController.swift```  and find this piece of code on line 13: 
` protocol WebViewProtocol `
and change it to: 
` @objc protocol WebViewProtocol`

--------------------------------------------------------------------------------------------

Next error is what ramki1979 said: there are some string errors in some files. One you can fix is this:
` if count(queryString.utf16) == 0 `
Just change it to a property, not a function: 
`if queryString.length() == 0 `


Bascially, if you ever see 
`count(stringName.utf16)`
Just change it to 
`stringName.count`


Also another example under `String+OAuthSwift.swift` you will find this: 
`    func length()->Int{
        return count(self)
    }`

which should just return: 
`return self.count()`
--------------------------------------------------------------------------------------------
Hope I helped you guys. Tell me if I missed anything!

**Comment by ejpusa** [comment]
Ok, almost@  Down to 1 error, tried a number of permutations, still bugs out. Thanks for all your help gabriel-jones. 
![screen shot 2015-04-11 at 4 07 53 pm](https://cloud.githubusercontent.com/assets/1279819/7103091/3ece784e-e065-11e4-9644-e02f7e735000.png)

**Comment by ejpusa** [comment]
Got it!  Thanks
![screen shot 2015-04-11 at 4 07 53 pm](https://cloud.githubusercontent.com/assets/1279819/7103108/add6cff2-e065-11e4-8698-629f3f111ad0.png)

**Comment by ejpusa** [comment]
Got it!  Thanks!
![screen shot 2015-04-11 at 4 13 59 pm](https://cloud.githubusercontent.com/assets/1279819/7103112/cf14154e-e065-11e4-9bb1-1c285a15fac2.png)

**Comment by ejpusa** [comment]
Almost! 
![screen shot 2015-04-11 at 4 18 39 pm](https://cloud.githubusercontent.com/assets/1279819/7103123/80f741fa-e066-11e4-8581-9098b59bbc19.png)

**Comment by phimage** [comment]
@TarangKhanna please close this old github issue
(only you or project owner can do it)
