### ISSUE TITLE
Carthage update fails

### ISSUE THREAD

**Issue by larabear** [dongri/OAuthSwift#33]
I made the cartfile, but when I did carthage update it fails. Help? Thanks!

*** Fetching OAuthSwift
*** Checking out OAuthSwift at "v0.3.2"
*** xcodebuild output can be found in /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/carthage-xcodebuild.ItCH7l.log
*** Building scheme "OAuthSwift" in OAuthSwift.xcodeproj
2015-03-13 15:33:31.829 xcodebuild[7699:57000]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6269/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuth1Swift.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “OAuth1Swift.d” couldn’t be opened because there is no such file." UserInfo=0x7fd8e55af210 {NSFilePath=/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuth1Swift.d, NSUnderlyingError=0x7fd8e5591ea0 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuth1Swift.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fd8e5590fe0>{number = 7, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-03-13 15:33:31.847 xcodebuild[7699:57000]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6269/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuth2Swift.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “OAuth2Swift.d” couldn’t be opened because there is no such file." UserInfo=0x7fd8e354b090 {NSFilePath=/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuth2Swift.d, NSUnderlyingError=0x7fd8e3562a70 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuth2Swift.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fd8e5590fe0>{number = 7, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-03-13 15:33:31.863 xcodebuild[7699:57000]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6269/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/String+OAuthSwift.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “String+OAuthSwift.d” couldn’t be opened because there is no such file." UserInfo=0x7fd8e372aaf0 {NSFilePath=/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/String+OAuthSwift.d, NSUnderlyingError=0x7fd8e3715c10 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/String+OAuthSwift.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fd8e5590fe0>{number = 7, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-03-13 15:33:31.879 xcodebuild[7699:57000]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6269/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuthSwiftClient.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “OAuthSwiftClient.d” couldn’t be opened because there is no such file." UserInfo=0x7fd8e37299f0 {NSFilePath=/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuthSwiftClient.d, NSUnderlyingError=0x7fd8e372eef0 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuthSwiftClient.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fd8e5590fe0>{number = 7, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-03-13 15:33:31.895 xcodebuild[7699:57000]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6269/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuthSwiftCredential.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “OAuthSwiftCredential.d” couldn’t be opened because there is no such file." UserInfo=0x7fd8e56435c0 {NSFilePath=/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuthSwiftCredential.d, NSUnderlyingError=0x7fd8e3552b30 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuthSwiftCredential.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fd8e5590fe0>{number = 7, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-03-13 15:33:31.911 xcodebuild[7699:57000]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6269/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/Utils.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “Utils.d” couldn’t be opened because there is no such file." UserInfo=0x7fd8e57679e0 {NSFilePath=/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/Utils.d, NSUnderlyingError=0x7fd8e5767ae0 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/Utils.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fd8e5590fe0>{number = 7, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-03-13 15:33:31.928 xcodebuild[7699:57000]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6269/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/SHA1.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “SHA1.d” couldn’t be opened because there is no such file." UserInfo=0x7fd8e3553740 {NSFilePath=/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/SHA1.d, NSUnderlyingError=0x7fd8e56a48c0 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/SHA1.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fd8e5590fe0>{number = 7, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-03-13 15:33:31.946 xcodebuild[7699:57000]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6269/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/NSURL+OAuthSwift.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “NSURL+OAuthSwift.d” couldn’t be opened because there is no such file." UserInfo=0x7fd8e5700040 {NSFilePath=/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/NSURL+OAuthSwift.d, NSUnderlyingError=0x7fd8e3553390 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/NSURL+OAuthSwift.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fd8e5590fe0>{number = 7, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-03-13 15:33:31.962 xcodebuild[7699:57000]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6269/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuthSwiftHTTPRequest.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “OAuthSwiftHTTPRequest.d” couldn’t be opened because there is no such file." UserInfo=0x7fd8e3723090 {NSFilePath=/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuthSwiftHTTPRequest.d, NSUnderlyingError=0x7fd8e3565f80 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuthSwiftHTTPRequest.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fd8e5590fe0>{number = 7, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-03-13 15:33:31.981 xcodebuild[7699:57000]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6269/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/Int+OAuthSwift.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “Int+OAuthSwift.d” couldn’t be opened because there is no such file." UserInfo=0x7fd8e35684b0 {NSFilePath=/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/Int+OAuthSwift.d, NSUnderlyingError=0x7fd8e566c780 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/Int+OAuthSwift.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fd8e5590fe0>{number = 7, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-03-13 15:33:31.997 xcodebuild[7699:57000]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6269/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/Dictionary+OAuthSwift.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “Dictionary+OAuthSwift.d” couldn’t be opened because there is no such file." UserInfo=0x7fd8e37508e0 {NSFilePath=/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/Dictionary+OAuthSwift.d, NSUnderlyingError=0x7fd8e3718c30 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/Dictionary+OAuthSwift.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fd8e5590fe0>{number = 7, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-03-13 15:33:32.014 xcodebuild[7699:57000]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6269/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/NSData+OAuthSwift.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “NSData+OAuthSwift.d” couldn’t be opened because there is no such file." UserInfo=0x7fd8e3568660 {NSFilePath=/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/NSData+OAuthSwift.d, NSUnderlyingError=0x7fd8e372d260 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/NSData+OAuthSwift.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fd8e5590fe0>{number = 7, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-03-13 15:33:32.031 xcodebuild[7699:57000]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6269/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuthWebViewController.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “OAuthWebViewController.d” couldn’t be opened because there is no such file." UserInfo=0x7fd8e3751330 {NSFilePath=/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuthWebViewController.d, NSUnderlyingError=0x7fd8e35684f0 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/var/root/Library/Developer/Xcode/DerivedData/OAuthSwift-agmslwgnqnyoymdyahotljlieful/Build/Intermediates/OAuthSwift.build/Release-iphonesimulator/OAuthSwift.build/Objects-normal/i386/OAuthWebViewController.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fd8e5590fe0>{number = 7, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal i386 /Users/laralu/Documents/cart/Carthage/Checkouts/OAuthSwift/OAuthSwift/OAuth1Swift.swift
	CompileSwift normal i386 /Users/laralu/Documents/cart/Carthage/Checkouts/OAuthSwift/OAuthSwift/OAuth2Swift.swift
	CompileSwift normal i386 /Users/laralu/Documents/cart/Carthage/Checkouts/OAuthSwift/OAuthSwift/String+OAuthSwift.swift
	CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
(4 failures)

**Comment by phimage** [comment]
This is a very old bug, I will close
If someone have issue with Carthage, please open an other issue
