### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by Niels-P** [dongri/OAuthSwift#38]
When I run the following code in the emulator on a virtual device it runs without a problem, but when I run it on a real iPhone 6 it gives me the following error. Anyone that has a solution for this problem? I run currently (Xcode 6.2 with branche OAuthSwift-ad0f2ecca892e3bd309f09eeb8f591036faebacb) so that's not swift 1.2. 

```
dyld: Library not loaded: @rpath/OAuthSwift.framework/OAuthSwift
  Referenced from: /private/var/mobile/Containers/Bundle/Application/4491E67B-580A-430F-84F3-E571CCD1B184/LinkingSkills.app/LinkingSkills
  Reason: image not found
(lldb) 
```

```
import UIKit
import OAuthSwift

class LinkedinLoginViewController: UIViewController, NSXMLParserDelegate {
    let dataString = NSString();
    var parser = NSXMLParser()
    var posts = NSMutableArray()
    var elements = NSMutableDictionary()
    var element = NSString()
    
    var voornaam = NSMutableString()
    var achternaam = NSMutableString()
    var skills = NSMutableArray()
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
}
```

**Comment by hopye** [comment]
This is also happening to me, can someone explain how to fix ???

**Comment by hopye** [comment]
xcode 6.2, swift 1.1

**Comment by gabriel-jones** [comment]
I once had a problem like this where it was looking for the files under the directory for .../iphone/... instead of .../iphone-simulator/...

Maybe try changing this?

**Comment by hopye** [comment]
Thanks a lot, i already had like an hour looking for this, and after writing here i think i have found it. it is working now. I had to Select my main Project workspace. GENERAL TAB -> EMBED BINARIES and include the OauthSwift Framework there, also in LINKED FRAMEWORKS AND LIBRARIES. This is apart from including it in Build Phases -> target dependencies and Link with binaries... Thanks a lot For Replying!!!

**Comment by jdbateman** [comment]
Same problem on Xcode 7.3.1 building for iPhone running iOS 9.3. Thanks a million hopye for pointing me in the right direction! I had OAuthSwift.framework listed in my Target > Build Phases > Link Binary with Libraries producing the similar failure at runtime. Adding the same framework to my Target > General > Embedded Libraries and my Target > General > Linked Frameworks and Libraries fixed the runtime error.

**Comment by hopye** [comment]
@jdbateman Best Regards!
