### ISSUE TITLE
OAuthSwift and Quickbooks API?

### ISSUE THREAD

**Issue by gabriel-jones** [dongri/OAuthSwift#39]
Does this library work with the Quickbooks API? If so, how can I do a request?

**Comment by dongri** [comment]
Added Quickbooks API
https://github.com/dongri/OAuthSwift/commit/0abc2b8a453662e7e97f53e80abb6b80df0c4cca

**Comment by nabil-takla** [comment]
Thanks! Are you planning to add Facebook API? 


Nabil Takla
Founder and CEO
N3Ventures LLC
nabil.takla@n3ventures.com
+1.415.810.8058
Skype: ntakla
http://www.n3ventures.com

This e-mail is for the sole use of the intended recipient(s). It contains information that is confidential. If you believe that it has been sent to you in error, please notify the sender by reply e-mail and delete the message. Any disclosure, copying, distribution or use of this information by someone other than intended recipient is prohibited.
