### ISSUE TITLE
oauth_token in request?

### ISSUE THREAD

**Issue by gabriel-jones** [dongri/OAuthSwift#40]
Under the OAuthSwiftClient, authorizationHeaderForMethod function, the authorisation parameters do not include oauth_token when I try to do a request. I tested it out, and oauth_token is an empty string, so it's not being included. I think this is why my request is not working -- can anybody tell me how to include the oauth_token into the request? 

I'm initialising the OAuth1Swift class in my main View Controller. Therefore I don't think I can get the oauth_token until I initialise it, which is not happening before the authorizationHeaderForMethod, so I don't get a value. Any ideas?

**Comment by Berdikhan** [comment]
I have a same issue...
I want to do a GET request, but I got token_rejected error message (I did authentication before and I have an access token)
