### ISSUE TITLE
Can´t build the project

### ISSUE THREAD

**Issue by JValderramaN** [dongri/OAuthSwift#41]
Hello, I was trying to use your repo, but when build its fail. idk why, please help. Im interested on this repo. Adjunct the representative image

![screen shot 2015-03-30 at 9 23 07 am](https://cloud.githubusercontent.com/assets/8615928/6897661/dc872898-d6be-11e4-82a9-e3b02f6bb9a5.png)

**Comment by gabriel-jones** [comment]
Same problem, not sure how to fix.

**Comment by gabriel-jones** [comment]
See #31 for details.

**Comment by phimage** [comment]
@JValderramaN  please close

**Comment by JValderramaN** [comment]
Hi there, how is it? Close what?


2015-08-07 16:13 GMT-04:30 Phi Mage <notifications@github.com>:

> @JValderramaN <https://github.com/JValderramaN> please close
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dongri/OAuthSwift/issues/41#issuecomment-128830260>.
>



-- 
José Valderrama
04249723244

**Comment by phimage** [comment]
this #41 issue is a duplicate from #31
please come to github and close the issue you have created (only you or the owner(busy) of the project can close)
