### ISSUE TITLE
OAuth1 signature error (HMAC & SHA1)

### ISSUE THREAD

**Issue by ramki1979** [dongri/OAuthSwift#42]
I manually included all files in my project target for iOS 7, and when I try to log into linkedin I got a Signature Invalid exception. After debugging The base string is correct but the signature generated is wrong.  

OAuthSwift implemented its own HMAC and SHA1 algorithms, so I don't see I have to include any additional crypto libraries. 

Am I missing any project settings or libraries/frameworks.

**Comment by gabriel-jones** [comment]
Could you show us your signed url? Also, have you fixed the errors in the project shown in issue #31 ?

**Comment by ramki1979** [comment]
I use this online tool for signature verification:
http://oauth.googlecode.com/svn/code/javascript/example/signature.html

```
LinkedIn API Endpoint:
https://api.linkedin.com/uas/oauth/requestToken
CallBack_Url: oauth-swift://oauth-callback/linkedin

Base String:
POST&https%3A%2F%2Fapi.linkedin.com%2Fuas%2Foauth%2FrequestToken&oauth_callback%3Doauth-swift%253A%252F%252Foauth-callback%252Flinkedin%26oauth_consumer_key%3D75h09kl7bn1jlv%26oauth_nonce%3D3B933B52%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1428324880%26oauth_version%3D1.0

OAuth Swift Generated signature:
sign: <8e161214 efefeea1 bb9cf526 3aeb3df0 abc65ce7> 
jhYSFO/v7qG7nPUmOus98KvGXOc=

Online Tool Generated signature for the same base string:
5r3+m1qhP9q89YthDQQ4oKtDNyE=
```

I have developed my own oauth1 and oauth2 libraries in C [used opensource HMAC-sha1] for another mobile platform a couple of years back, so I am very well aware of OAuth 1 & 2 specs. 

As the same is working for other users, I feel I might missed some swift knowledge or settings here.

**Comment by ramki1979** [comment]
This issue is related to OAuthSwift fork https://github.com/WazzeZ/OAuthSwift,

closing this issue.
