### ISSUE TITLE
Callback URL

### ISSUE THREAD

**Issue by Berdikhan** [dongri/OAuthSwift#43]
Hi everyone
When I set the callback URL to my own application it gives error
Error Domain=NSURLErrorDomain Code=400 "HTTP Status 400: Bad Request, Response: oauth_problem=parameter_rejected&message=oauth_callback" UserInfo=0x7c8b4e80
But when I set the callback url to my website it works.
And another issue is that I cannot handle the access token and access token secret, I can only see it in a url attached such as "http://website.com?access_token=sdjflkdjsf&access_token_secret=asdasdasd"
```
func Authenthication(){
        let client = OAuth1Swift(
            consumerKey: "consumerkey",
            consumerSecret: "consumersecret",
            requestTokenUrl: "http://192.168.54.35/ergasia/oauth/initiate",
            authorizeUrl: "http://192.168.54.35/ergasia/oauth/authorize",
            accessTokenUrl: "http://192.168.54.35/ergasia/oauth/token")
        client.webViewController = WebViewController()
        client.authorizeWithCallbackURL(NSURL(string: "nettium://")!, success: { credential, response in
            println("\(credential.oauth_token)")
            self.credent = credential
        }) { (error) -> Void in
            println(error)
        }
    }
```
If I do in this way everything works, except it does not show an alertView and cannot get an access token
```
        client.authorizeWithCallbackURL(NSURL(string: "http://192.168.54.35/ergasia/customer/account")!, success: { credential, response in
            self.showAlertView("Magento", message: "auth_token:\(credential.oauth_token)\n\noauth_toke_secret:\(credential.oauth_token_secret)")
            println("\(credential.oauth_token)")
        }) { (error) -> Void in
            println(error)
        }
```
Any ideas? Need help, thanks

**Comment by gabriel-jones** [comment]
The callback url should be `oauth-swift://oauth-callback/application_name` -- does this not work?

**Comment by Berdikhan** [comment]
Nope, I set the same URL as previous, just handled it from WebViewController. I saved tokens to NSUserDefaults. And created clients using saved tokens. Now it works fine
