### ISSUE TITLE
Why demoapp prefers safari over webview

### ISSUE THREAD

**Issue by ramki1979** [dongri/OAuthSwift#45]
I have seen quite a few posts on internet about appstore rejections for using safari for OAuth login instead of webview.

**Comment by zavada** [comment]
+1

**Comment by zavada** [comment]
@ramki1979 I have found the example with webview. Just uncomment in the ViewController.swift for twitter
```
oauthswift.webViewController = WebViewController()
```

**Comment by ramki1979** [comment]
I have already done that, But just want to know If I miss something relative to security.
I have also created an OAuthSDK that supports 1 & 2 @ https://github.com/ramki1979/OAuthSDK.

**Comment by eitanjt** [comment]
Hi, i used the example whit the "oauthswift.webViewController = WebViewController()" uncommented, and yes it works, but still it doesn't let me to manage the interface, id like to call the login in a uiwebview, can anyone help me to do this?

**Comment by phimage** [comment]
@eitanjt go to #63 (#69)

**Comment by phimage** [comment]
@ramki1979 please close this issue

OAuthSwift could use webview with authorize_url_handler attribute
(OAuthWebViewController is provided as "abstract" controller, and demo code WebViewController show how to use it)
