### ISSUE TITLE
Lots of errors, am I doing something basically wrong? Clean install. Swift, 6.2

### ISSUE THREAD

**Issue by ejpusa** [dongri/OAuthSwift#50]
![screen shot 2015-04-11 at 2 39 21 pm](https://cloud.githubusercontent.com/assets/1279819/7102761/c8d60384-e058-11e4-82e8-bf889674f3b1.png)

**Comment by gabriel-jones** [comment]
Explained on Issue #31 by me.

**Comment by ejpusa** [comment]
Cool, thank for the quick reply. Tackling all now.  :-)

On Sat, Apr 11, 2015 at 2:53 PM, gabriel-jones <notifications@github.com>
wrote:

> Explained on Issue #31 <https://github.com/dongri/OAuthSwift/issues/31>
> by me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dongri/OAuthSwift/issues/50#issuecomment-91902262>.
>



-- 
____________
twitter: twitter.com/ejpusa
iPhone portfolio: http://www.preceptress.com

**Comment by gabriel-jones** [comment]
Has the issue been resolved? If so, close the issue.
