### ISSUE TITLE
Almost!  Crashing on Instagram with latest build. 

### ISSUE THREAD

**Issue by ejpusa** [dongri/OAuthSwift#52]
1. DL latest build
2. Set up Podfile
3. Add my ID, and secret key. That's it. Pretty simple.
4. Run Demo

OAuth verification on mobile is not easy, that we know.

Kaboom!  What the heck is going on. I'm confused a bit by this one. There is nothing optional here. Error does not show up at compile time. Only at run time. So close! Thanks.

![screen shot 2015-04-13 at 8 33 48 pm](https://cloud.githubusercontent.com/assets/1279819/7128173/96600d1c-e21c-11e4-882e-ff76e0d08eea.png)

**Comment by ejpusa** [comment]
Ok, started from scratch, worked.

**Comment by gabriel-jones** [comment]
`Instagram["consumerKey"]` instead of `Instagram[4612379641789]` would've worked.

**Comment by ejpusa** [comment]
Got it thanks. Yes, missed the constants.swift file. Guess what threw me was the error message. thanks :-)
