### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by alikazim** [dongri/OAuthSwift#55]
As suggested by the documentation, I did,

Drag OAuthSwift.xcodeproj to my project in the Project Navigator.
Selected my project and then my app target. Open the Build Phases panel.
Expand the Target Dependencies group, and add OAuthSwift framework.

and Build Failed, with no any error messages. please help

**Comment by ejpusa** [comment]
Works perfect:

Create your Podfile
pod install

--------------

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!
pod "OAuthSwift", "~> 0.3.3"
