### ISSUE TITLE
Add support for Uber Authentication

### ISSUE THREAD

**Issue by alikazim** [dongri/OAuthSwift#57]
Please add Uber User Authentication
https://developer.uber.com/v1/auth/

**Comment by sephethus** [comment]
I second this request!!

**Comment by phimage** [comment]
Have you try to use the framework to connect to uber? 
There is issue?

If not, this not an "issue" and an "add support" => just add uber to the demo projects 

If someone that use uber and OAuthSwift with success, please PR ;)

**Comment by sephethus** [comment]
There's a framework to connect to uber?

**Comment by phimage** [comment]
OAuthSwift is the OAuth swift framework...

Uber is OAUTH 2.0, so try it if you need it ...

**Comment by sephethus** [comment]
Oh yeah I already have the OAuthSwift framework I'm past that point. I'm trying to get uber to authenticate my user account with my app and I'm totally failing. I need examples for connecting with uber. I don't know if I'm doing the redirect_uri correctly, I don't know what to put for state or params or scope. I set up the url schema part with my app name, but other than that I'm stuck.

**Comment by sephethus** [comment]
let oauthUber = OAuth2Swift(consumerKey: CLIENT_KEY, consumerSecret: CLIENT_SECRET, authorizeUrl: REGISTER_URL, accessTokenUrl: ACCESS_TOKEN_URL, responseType: "code")
        let encodedRedirectURI = REDIRECT_URI.stringByAddingPercentEscapesUsingEncoding(NSUTF8StringEncoding)
        oauthUber.authorizeWithCallbackURL(REDIRECT_URI, scope: <#String#>, state: <#String#>, params: <#Dictionary<String, String>#>, success: <#TokenSuccessHandler##(credential: OAuthSwiftCredential, response: NSURLResponse?, parameters: NSDictionary) -> Void#>, failure: <#((error: NSError) -> Void)##(error: NSError) -> Void#>)

**Comment by phimage** [comment]
for code use markdown `
 ```swift 
let oauth...
 ````

for redirect URI see all examples in demo, its an url handled by your application or with custom protocol to be opened by your application

for scope see OAuth doc and Uber api (keywork to ask permission : generally read, etc..., for uber in example there is profile history)

I think this issue could be closed @dongri, already one here #59 talking about uber and problem

**Comment by sephethus** [comment]
I still get an error message with OAuthSwift that will not compile. See here: http://stackoverflow.com/questions/31765401/how-do-i-authorize-my-uber-account-in-swift-using-oauthswift

**Comment by phimage** [comment]
Missing `,parameters` after credential in success closure
...See all oauth2 example

I make a pr to have the samething for oauth1 (to keep coherence)

**Comment by sephethus** [comment]
I don't see that in the example anywhere. I added parameters back to the authorizeWithCallbackURL but I don't see what the parameters do or what their purpose is since I never set them anywhere.

**Comment by phimage** [comment]
@alikazim please close this generic issue
There is other issues with real information about uber problem like #59
