### ISSUE TITLE
Help getting instagram profile data

### ISSUE THREAD

**Issue by hopye** [dongri/OAuthSwift#58]
How can i get the users's profile data ? Username, id , etc..

In instagram theres no end like /user/me .

Instagram sends the profile info in the authentication process

**Comment by zavada** [comment]
You can find the example of api request in ViewController.swift. Look into func doOAuthInstagram().
```
let url :String = "https://api.instagram.com/v1/users/1574083/?access_token=\(credential.oauth_token)"
            let parameters :Dictionary = Dictionary<String, AnyObject>()
            oauthswift.client.get(url, parameters: parameters,
                success: {
                    data, response in
                    let jsonDict: AnyObject! = NSJSONSerialization.JSONObjectWithData(data, options: nil, error: nil)
                    println(jsonDict)
                }, failure: {(error:NSError!) -> Void in
                    println(error)
            })
```
Just change get request.

**Comment by gabriel-jones** [comment]
Also, documentation on Instagram (you can see the console here: https://instagram.com/developer/api-console/) shows that a request would be to "https://api.instagram.com/v1/users/self" for the data of the person who logged in, or a specific ID in place of 'self' would retrieve data for that user.

**Comment by hopye** [comment]
omg.. i didn't know instagram had a users/self !@@ ill check that right now!! thnx!

**Comment by hopye** [comment]
i got it!, How can i send a deauthententicate to instagram, like... the user wants to log out..

**Comment by ejpusa** [comment]
You may want to look into SwiftyJSON. Makes JSON parsing super simple, and that gets you pretty much everything from your IG response object.

https://github.com/SwiftyJSON/SwiftyJSON/tree/master

**Comment by phimage** [comment]
@hopye please close this issue, initial question has been answered

for a new question  new issue but I can try to repond.
 The User doesn't logout, its just you that do not use the token anymore 
There is no "revoke token" currently in instagram api ( https://instagram.com/developer/authentication/ ) to invalidate token and maybe no expiration time that can be specified by you
