### ISSUE TITLE
401

### ISSUE THREAD

**Issue by amycheong19** [dongri/OAuthSwift#61]
I'm using the same link and I tried to access it from POSTMAN and it worked so I tried it in mobile but it ended up return 401 http error. Is there anything i missed out?

![screen shot 2015-05-08 at 7 44 14 am](https://cloud.githubusercontent.com/assets/9781961/7528108/15449b6a-f556-11e4-8d8f-e63cf7040dcb.png)

    func doOAuthTwitter(){
        let oauthswift = OAuth1Swift(
            consumerKey:    Twitter["consumerKey"]!,
            consumerSecret: Twitter["consumerSecret"]!,
            requestTokenUrl: "https://api.twitter.com/oauth/request_token",
            authorizeUrl:    "https://api.twitter.com/oauth/authorize",
            accessTokenUrl:  "https://api.twitter.com/oauth/access_token"
        )
        
        //oauthswift.webViewController = WebViewController()
        oauthswift.authorizeWithCallbackURL( NSURL(string: "oauth-swift://oauth-callback/twitter")!, success: {
            credential, response in
            self.showAlertView("Twitter", message: "auth_token:\(credential.oauth_token)\n\noauth_toke_secret:\(credential.oauth_token_secret)")
            var parameters =  Dictionary<String, AnyObject>()
            oauthswift.client.get("https://api.twitter.com/1.1/account/verify_credentials.json?skip_status=true&include_email=true", parameters: parameters,
                success: {
                    data, response in
                    let jsonDict: AnyObject! = NSJSONSerialization.JSONObjectWithData(data, options: nil, error: nil)
                    println(jsonDict)
                }, failure: {(error:NSError!) -> Void in
                    println(error)
                })
            
            }, failure: {(error:NSError!) -> Void in
                println(error.localizedDescription)
            }
        )
    }

**Comment by BCGray00** [comment]
Same here, any solution?

**Comment by fewspider** [comment]
Make sure your app has the login permission. 
You can setting it in `https://apps.twitter.com/app/5250618/settings` ,`5250618` is my app id,use your app id to replace it.
It will be working.

![demo](https://cloud.githubusercontent.com/assets/3256161/8765620/0361b37c-2e47-11e5-8d4e-67266677758f.png)

**Comment by phimage** [comment]
@amycheong19 please close this issue
