### ISSUE TITLE
Modify webview

### ISSUE THREAD

**Issue by hopye** [dongri/OAuthSwift#63]
Guys, i know this is probably a lame question, but.. How can i modify de webview ? In my app i have everyrhing under a navigation crontoller, when login in with the oauthswift , i get ro this plain blank uiviewcontroller in blank, it takes the whole screen .. I get instagram textfields and interface almost overlapoing the status bar. I would like to get that webview viewconteoller inside of my navigstion controller etc

**Comment by phimage** [comment]
I created a pull request that may fulfill your request.
https://github.com/dongri/OAuthSwift/pull/62
I add a handler instead of affecting web view controller in OAuth object where you can to control the web view displaying

**Comment by hopye** [comment]
Can you please show me some code ??

**Comment by phimage** [comment]
pull request has been merged :)

make your navigation controller(or other object) implement the new interface `OAuthSwiftURLHandlerType` 
in the handle(url) method you can call method of your navigation controller to display the web view and also set the url to it

then assign the object to the oauthswift object
``` swift
oauthswift.authorize_url_handler = <your object>
```

**Comment by hopye** [comment]
phimage and dondri, im still using swift 1.1 , do you have the latest modified code for swift 1.1 ?

**Comment by phimage** [comment]
No, why not upgrade Xcode ans Swift?
If you insist to have my commit on swift1.1 you must do some git

Clone the repo, make a branch at specific commit hash you use
Do a cherry pick on my commit hash and the following dondri fix. Fix all the issues and resolve conflits 
Two much work for nothing!

I think issue can be closed

**Comment by hopye** [comment]
i downloaded te repo, basically modified all as! to as , modify the count(variable.utf16) to just variable.utf16Count , it did compiled..

**Comment by hopye** [comment]
phimage, can you please modify my example on how to implement with the nav controller ? please..
https://github.com/hopye/OauthTest/tree/master/pruebaOAUTH

**Comment by alexdd55** [comment]
@hopye how did you manage to do this.. for me its always opening safari for auth :(

**Comment by phimage** [comment]
@alexdd55 did you open hopye test projet, I update with storyboard segue. 
Other way is to watch current project sample, just affect authorize_url_handler

**Comment by alexdd55** [comment]
@phimage authorize_url_handler does not has any influence, also it seems it is not available for oauth1swift

**Comment by phimage** [comment]
it is available... maybe you use old code, just watch current code

just affect it with your own handler, not the default one OAuthSwiftOpenURLExternally.sharedInstance which open url with safari

the handler receive the url to open in webview, and is reponsible to display the webview (many way to do it and Demo and hopye project show it)

**Comment by alexdd55** [comment]
i think i made it work, i thought there might be some parameter that i missed

**Comment by hopye** [comment]
@alex i will commit the example so you see, @phimage guided my code ;) . I did modify to work under swift 1.1 thought...

**Comment by hopye** [comment]
Let us know :) ;)

**Comment by alexdd55** [comment]
i had to make a couple of changes to make that work with Twitter OAuth1 + swifter, also also customized notitication so my own methods will be called.
no buildin handler worked for me whysoever. Can't update OAuth anymore from now on

**Comment by phimage** [comment]
so make your fork, commit change then we can compare and you can merge from upstream if you want (if the change are not big)

notification work well on my project, handleOpenURL method must be called for that

 I use two way
1 - normal way: my internal webview don't open url with scheme set in callback url( ex: oauth-swift), I open the callback url externally, and because the application is(must be) registered to open this type of url scheme, in appDelegate, like in the demo, the url is handled and passed to handleOpenURL
2 - my favorite way : in webview delegate when the url scheme of callback url is detected I call directly the handleOpenURL

**Comment by phimage** [comment]
@hopye could you close the issue?
