### ISSUE TITLE
Problem with authenticating via Tumblr

### ISSUE THREAD

**Issue by pschneider** [dongri/OAuthSwift#65]
Hi,

I'm currently trying to authenticate via Tumblr OAuth1. Unfortunately I'm always getting the following error when coming back from Mobile Safari:

```
Error Domain=oauthswift.error Code=-1 "The operation couldn’t be completed. Oauth problem." UserInfo=0x7fc56290abe0 {NSLocalizedFailureReason=Oauth problem.}
```

I'm using the following URLs as mentioned on [Tumblr docs](https://www.tumblr.com/docs/en/api/v2#auth)
```
let requestTokenURL = "http://www.tumblr.com/oauth/request_token"
let authorizeURL = "http://www.tumblr.com/oauth/authorize"
let accessTokenURL = "http://www.tumblr.com/oauth/access_token"
```
Tumblr's documentation stated that their implementation is very similar with Twitter, but if I change the key/secret and the URLs to Twitter's API everything works fine.

Does anyone know what kind of problem I'm facing here? Could this be an Issue with the OAuth Library itself?

Thanks!

Edit: Tumblr Sends valid oauth_token and oauth_verifier Parameters back. The url looks just like when authenticating against twitter.

**Comment by venox** [comment]
The problem seems to be that Tumblr adds the following URL fragment at the end of the callback: #_=_
So the parameters are overwritten in authorizeWithCallbackURL.

```
// until here everything is fine for both
if ((url.fragment) != nil && url.fragment!.isEmpty == false) {
    println("Tumblr goes here")
    parameters = url.fragment!.parametersFromQueryString()
} else {
    println("Twitter goes here")
}
// parameters for Tumblr are nil, Twitter is fine
```

**Comment by dongri** [comment]
Fix:
https://github.com/dongri/OAuthSwift/commit/1babc0f465144411c0dd9721271f239685ce83a9

**Comment by pschneider** [comment]
Thank you @dongri !
