### ISSUE TITLE
Trying to have a Cancel for Instagram and also have it flush to the top of the window.

### ISSUE THREAD

**Issue by ejpusa** [dongri/OAuthSwift#69]
Tried a number of things, but since the WebView is not created in a storyboard, seems i'm not able to position it. Wondering if there is a work around for these 2 needed features:

1. Where the Instagram Login screen appears.
2. A Cancel button on the first Instagram screen.

![screen shot 2015-05-23 at 10 24 19 pm](https://cloud.githubusercontent.com/assets/1279819/7786408/834d9b3e-019a-11e5-9bf3-e2f86e525559.png)

**Comment by phimage** [comment]
with current master branch you can show your own webview with storyboard and add a cancel button 
your own controller, action, etc...

see an example here https://github.com/hopye/OauthTest/tree/master/pruebaOAUTH/pruebaOAUTH
from #63

**Comment by phimage** [comment]
@ejpusa could you close? (demo provided by the link in my previous comment show how to work with storyboard)
