### ISSUE TITLE
OAuthSwiftClient fix

### ISSUE THREAD

**Issue by ozgurersil** [dongri/OAuthSwift#70]
In OAuthSwiftClient.swift class:

in request function if the url contains latin chars, NSURL crashes. I fix and paste below

    func request(url: String, method: String, parameters: Dictionary<String, AnyObject>, success: OAuthSwiftHTTPRequest.SuccessHandler?, failure: OAuthSwiftHTTPRequest.FailureHandler?) {
        if let url = NSURL(string: url.stringByAddingPercentEscapesUsingEncoding(NSUTF8StringEncoding)!)
        {
            let request = OAuthSwiftHTTPRequest(URL: url, method: method, parameters: parameters)
            if self.credential.oauth2 {
                request.headers = ["Authorization": "Bearer \(self.credential.oauth_token)"]
            } else {
                request.headers = ["Authorization": OAuthSwiftClient.authorizationHeaderForMethod(method, url: url, parameters: parameters, credential: self.credential)]
            }
            request.successHandler = success
            request.failureHandler = failure
            request.dataEncoding = dataEncoding
            request.encodeParameters = true
            request.start()
        }
    }

thanks for the library,
it rocks

**Comment by phimage** [comment]
PR  #71 opened
