### ISSUE TITLE
Yelp example

### ISSUE THREAD

**Issue by derrickshowers** [dongri/OAuthSwift#74]
Is there any way to add an example for how this can be used for Yelp? Seems that [their API](https://www.yelp.com/developers/documentation/v2/authentication) is different from others because the token is already provided and therefore there is not an endpoint available to retrieve the token. I'm hoping there is a way with your framework to manually provide the token?

**Comment by derrickshowers** [comment]
Submitted a [pull request](https://github.com/dongri/OAuthSwift/pull/75) for this.

**Comment by phimage** [comment]
I will close this issue
I repost here my comment on PR

Instanciate the OAuthSwift object as usual
Then access, using getter , the client and the credential, then set the token & token secret from conf using property setter

```swift

 let oauth = OAuth1Swift (
...
 )

oauth.client.credential.oauth_token =  mytoken
oauth.client.credential.oauth_token_secret = mytoken_secret
oauth.client.credential.oauth_header_type = "oauth1" // just a fix because not initialized at init yet

```
