### ISSUE TITLE
Custom oauth2 access

### ISSUE THREAD

**Issue by ctippur** [dongri/OAuthSwift#76]
Hello,
I am trying a custom oauth2 access and I am new to swift.

I am following instruction from https://django-oauth-toolkit.readthedocs.org/en/0.3.2/tutorial/rest_framework_integration.html.

The authorization process is 
Use initial username and password to get a token
Use the token to perform further api calls.

In my case, there is only accessTokenUrl and authorizeUrl is not applicable. Wondering how to proceed further. 
Appreciate any inputs.

- S

  func doOAuthScreener(){

        let oauthswift = OAuth2Swift(

            //https://django-oauth-toolkit.readthedocs.org/en/latest/rest-framework/getting_started.html

            consumerKey:    Screener["consumerKey"]!,

            consumerSecret: Screener["consumerSecret"]!,

            authorizeUrl:   HERE, 

            accessTokenUrl: HERE, // This seem to be http://localhost:8000/o/token/

            responseType:   "code"

        )

        

        

        let state: String = generateStateWithLength(20) as String

        

        

        oauthswift.authorizeWithCallbackURL( NSURL(string: "HERE")!, scope: "user,repo", state: state, success: {

            credential, response, parameters in

            self.showAlertView("Screener", message: "oauth_token:\(credential.oauth_token)")

            }, failure: {(error:NSError!) -> Void in

                println(error.localizedDescription)

        })    

    }

**Comment by phimage** [comment]
django not follow the protocol
So you can use any network framework or Foundation classes like NSMutableRequest to make a request
```
method = POST 
url = http://<client_id>:<client_secret>@localhostoryoururl:8000/o/token/
query param = “grant_type=password&username=<user_name>&password=<password>” 
```

I have no idea how to do this with OauthSwift
you can just set the token after retrieved it into OAuthSwift objects
