### ISSUE TITLE
Get login info from Callback?

### ISSUE THREAD

**Issue by gabriel-jones** [dongri/OAuthSwift#81]
How could I get the employee's unique ID from them logging in to the app connect page in Quickbooks? In other words, how can I access the callback's parameters sent back by Quickbooks so I can use that for other tasks?

**Comment by phimage** [comment]
Provide some codes, api link if it is not "intuit" api. Is it OAuth1?

**Comment by gabriel-jones** [comment]
The API uses OAuth1. It is the Quickbooks API, and calls are made to this endpoint: "https://sandbox-quickbooks.api.intuit.com/v3/company/<company_id>/", and the login is at this link: https://appcenter.intuit.com/Connect/Begin

**Comment by phimage** [comment]
maybe PR #79 is the solution, parameters returned by server is added to success callback

**Comment by phimage** [comment]
I closed my PR #79 due to conflit, need to make a new one
