### ISSUE TITLE
Swift 2.0 / Xcode 7 Support

### ISSUE THREAD

**Issue by rpowelll** [dongri/OAuthSwift#82]
What plans are there to support Swift 2.0 with OAuthSwift?

**Comment by gabriel-jones** [comment]
I'm guessing dongri and phimage will update the project when Xcode 7 and Swift 2 are officially released. In the meantime, I guess you can try Apple's swift converter in Xcode 7, which (mostly accurately) converts your old swift files to swift 2.0 files.

**Comment by rpowelll** [comment]
Surely they'd be working to get it updated ahead of time though? What I'd ideally like is a Swift 2 development branch that can be merged into `master` when the GM seed comes out.

**Comment by ejpusa** [comment]
If you use only one site to authenticate too, it's a great project to convert that piece to Swift 2. Hack away. And you'll learn lots. OAuth is probably one of the top topics in Comp Sci these days, everyone is into security, and a great piece of code to learn from.

**Comment by mwermuth** [comment]
Hey I am working on a Swift 2.0 version. I have it already running. But I made some additional changes to use it with Youtube and the new SFSafariViewController, because I needed it for an app I am working on. I will clean it out and make a Pull Request to have a swift2.0 dev branch here. In the meantime you can have a look here: https://github.com/mwermuth/OAuthSwift/tree/swift2.0

**Comment by crewshin** [comment]
+1 for a swift2 branch.

**Comment by driver733** [comment]
+1 for swift 2.0 support

**Comment by pschneider** [comment]
@mwermuth works fine for me so far. thanks :)

**Comment by driver733** [comment]
@mwermuth thanks too!

**Comment by MathijsK93** [comment]
Maybe a stupid question, but how can i use @mwermuth his fork in my xcode project? The podfile is referenced to the original OAuthSwift..

**Comment by pschneider** [comment]
Easiest way is to use Carthage. There you can specify his repo and add "swift2.0" at the end to use the specific swift 2 branch. 

I believe to do this with CocoaPods you need to fork and edit the podspec but not sure.

**Comment by mwermuth** [comment]
It does not matter whats written in the podspec you can specify the repo and branch in the Podfile. I am using it like this 
```
pod 'OAuthSwift', :git => 'https://github.com/mwermuth/OAuthSwift.git', :branch => 'swift2.0'
```

**Comment by damianesteban** [comment]
This is excellent, thank you.

**Comment by mwermuth** [comment]
I need to adopt the latest changed in XCode 6 beta 7. I will try to submit the change in the upcoming week.

**Comment by mwermuth** [comment]
I pushed some Swift 2.0 XCode 7 GM changes to my fork. I still need to se if everything works, but if anybody wants to check it out: https://github.com/mwermuth/OAuthSwift/tree/swift2.0

**Comment by phimage** [comment]
@mwermuth did you try to merge original master modifications since you create your swift2.0 branch?
(some bug fix, uber, ...)

**Comment by mwermuth** [comment]
@phimage Good one, not yet but will do :)

**Comment by phimage** [comment]
from 6e7b674a65348b57dc8b98ffeff523bd08f03222 to 1fcc3a1816792f11a226ae3b9ded7311e554e7c1 project owner implement swift2
@mwermuth you could compare if you take different path ;)

maybe issue could be closed now

**Comment by rpowelll** [comment]
:tada:
