### ISSUE TITLE
Tuple error using authorizeWithCallbackURL

### ISSUE THREAD

**Issue by sephethus** [dongri/OAuthSwift#86]
I can't get this method to compile. I get an error saying:

Tuple types '(credential: OAuthSwiftCredential, response: NSURLResponse?, parameters: NSDictionary)' and '(_,_)' have a different number of elements (3 vs. 2)

What am I doing wrong here?

```
let params = [String: String]()
let url = NSURL(string: REDIRECT_URI)
let oauthUber = OAuth2Swift(consumerKey: CLIENT_KEY, consumerSecret: CLIENT_SECRET, authorizeUrl: REGISTER_URL, responseType: "code")
        
oauthUber.authorizeWithCallbackURL(url!, scope: "profile history", state: "", params: params, success: {
        credentials, response in
            println("Success")
            println(credentials.oauth_token) },
        
        failure: { (error: NSError) -> Void in
            println("Fail")
 })

```

**Comment by sephethus** [comment]
Nevermind, I realized I left out parameters in the success closure. On to the next issue....

**Comment by phimage** [comment]
Please close
Check if parameters must be the last after response

**Comment by sephethus** [comment]
Neither order it's in seems to make it launch any URL in Safari...

**Comment by phimage** [comment]
You create an issue for that, please close this one about the tuple...
