### ISSUE TITLE
authorizeWithCallbackURL does nothing with Uber

### ISSUE THREAD

**Issue by sephethus** [dongri/OAuthSwift#87]
I execute the following but nothing happens:

```
    //UBER
    let REGISTER_URL = "https://login.uber.com/oauth/authorize"
    let CLIENT_KEY = "********************"
    let SERVER_TOKEN = "*********************"
    let CLIENT_SECRET = "**************************"
    let ACCESS_TOKEN_URL = "https://login.uber.com/oauth/token"
    let REDIRECT_URI = "myappname://callback/url"

    func registerWithUber() {
        let params = [String: String]()
        let url = NSURL(string: REDIRECT_URI)
        let oauthUber = OAuth2Swift(consumerKey: CLIENT_KEY, consumerSecret: CLIENT_SECRET, authorizeUrl: REGISTER_URL, responseType: "code")
        
        oauthUber.authorizeWithCallbackURL(url!, scope: "profile history", state: "", params: params, success: {
            credentials, parameters, response in
                println("Success")
                println(credentials.oauth_token) },
        
            failure: { (error: NSError) -> Void in
                println("Fail")
        })
   
    }
```

Shouldn't it launch the Safari browser to authenticate with Uber?

**Comment by sephethus** [comment]
I've also tried reversing parameters with response in the success closure but it doesn't change anything. Nothing happens. Nothing in the debug window.

**Comment by sephethus** [comment]
Further examination through the OAuthSwift method authorizeWithCallbackURL I found this does not happen here:
```
        if let queryURL = NSURL(string: urlString) {
            println("This happens")
           self.authorize_url_handler.handle(queryURL)
        }
```

I tried println(urlString) and it looks fine as a URL. I'm not sure why it's not getting converted to NSURL here.

**Comment by phimage** [comment]
The value of urlstring is?
Maybe encoded, maybe special character hidden

**Comment by sephethus** [comment]
Ok I found the answer. The problem was that the scope was not being percent escaped. "profile history" had to be changed to "profile%20history". This could be fixed by updating that urlString to be percent escaped. 

Now I'm getting an entirely different error from uber's page: Invalid Request Parameters

**Comment by phimage** [comment]
So maybe a fix needed to encode scope

**Comment by sephethus** [comment]
Yes, this worked here:

```
        if let q = urlString.stringByAddingPercentEscapesUsingEncoding(NSUTF8StringEncoding) {
            println(q)
            if let queryURL = NSURL(string: q) {
                println("This happens too")
                self.authorize_url_handler.handle(queryURL)
            }
        }
```
However, I'm sure it could be written better.

I still get invalid request parameters though, so not sure what's up with that. This is the url it's sending to UBER:

https://login.uber.com/oauth/authorize?client_id=myclientiddisplayscorrectlyhere&redirect_uri=UGetMe://oauth&response_type=code&scope=profile%20history

**Comment by damianesteban** [comment]
I'm having the same issue with the GitHub example...`authorizeWithCallbackURL` currently does nothing.

**Comment by sephethus** [comment]
See above, you'll have to make sure the url string is percent encoded before being passed to the handle method. This is found in OAuth2Swift.swift, I had to add the above lines.

**Comment by damianesteban** [comment]
I'm working with the Swift 2 branch actually and I'm presenting the login screen with a `SFSafariViewController`.  I was convinced I was using it incorrectly, but this did the trick.  Thank you.

**Comment by dongri** [comment]
Hi @sephethus @phimage @damianesteban 

I Resolved Uber OAuth problem

https://github.com/dongri/OAuthSwift/pull/96/files

Thanks!

**Comment by sephethus** [comment]
dongri, there is still an issue in the authorizeWithCallBackURL. Uber gets an Invalid Request Parameters if the callback url is included in the URL string. I have to comment out that line `urlString += "&redirect_uri=\(callbackURL.absoluteString!)"` just to fix it.
