### ISSUE TITLE
Cannot decode raw data

### ISSUE THREAD

**Issue by orkhanalizade** [dongri/OAuthSwift#90]
When I forward to UIWebView for authorization it prints in Safari: "Cannot decode raw data"

**Comment by phimage** [comment]
Add info please
iOS ? Website api? Some code

**Comment by orkhanalizade** [comment]
Oh, sorry. I solve it, but the state doesn't work. I use this code:

func doOAuthLinkedin2(){
    let oauthswift = OAuth2Swift(
        consumerKey:    "XXXXXXXX",
        consumerSecret: "XXXXXXXX",
        authorizeUrl:   "https://www.linkedin.com/uas/oauth2/authorization",
        accessTokenUrl: "https://www.linkedin.com/uas/oauth2/accessToken",
        responseType:   "code"
    )
    let state: String = generateStateWithLength(20) as String
    oauthswift.authorizeWithCallbackURL( NSURL(string: "https://mysite.co/user/auth?authclient=linkedin")!, scope: "r_basicprofile", state: state, success: {
        credential, response, parameters in
        self.showAlertView("Linkedin2", message: "oauth_token:\(credential.oauth_token)")
        var parameters =  Dictionary<String, AnyObject>()
        oauthswift.client.get("https://api.linkedin.com/v1/people/~?format=json", parameters: parameters,
            success: {
                data, response in
                let dataString = NSString(data: data, encoding: NSUTF8StringEncoding)
                println(dataString)
            }, failure: {(error:NSError!) -> Void in
                println(error)
        })
        }, failure: {(error:NSError!) -> Void in
            println(error.localizedDescription)
    })
}

and it prints: Invalid auth state parameter. What is wrong?

**Comment by phimage** [comment]
you add comment and remove it?
"Oh, sorry. I solve it" you say in the comment
so please close the issue... (you can also explain what you doing wrong for others)

website is linkedin
http://stackoverflow.com/questions/31913992/invalid-auth-state-parameter-in-oauth2
in OAuthSwift there is no state check its seems..., so  CSRF attacks could be achieve (issue needed for that)
