### ISSUE TITLE
user defined params in authorize phrase not supported

### ISSUE THREAD

**Issue by sunweik** [dongri/OAuthSwift#91]
certain service, such as flickr, needs to use 'perms=read' in authorize url to specify permission requested.  I don't see this is supported in latest version yet.

supporting user defined parameter for authorize url can fix this problem and more

**Comment by phimage** [comment]
With oauth2 the equivalent parameter is scope and there is also a dictionary parameters
But Flickr use oauth1 and there is no parameters
So the current workaround is to specify the url with the query parameter ie. ....authorize?perm=read

**Comment by sunweik** [comment]
this is a good workaround, I will check it out

**Comment by sunweik** [comment]
this workaround works
