### ISSUE TITLE
credential.auth2 variable is not automatically set to 'true' when using OAuth2Swift

### ISSUE THREAD

**Issue by twistify** [dongri/OAuthSwift#94]
the `oauth2` variable in `OAuthSwiftCredential` does not get set to `true` when authorizing with OAuth2.  This means that the client does not use oauth2 headers (`request.headers = ["Authorization": "Bearer \(self.credential.oauth_token)"]`) when making network requests.

While this can be worked around by explicitly setting the `oauth2` variable to `true`, shouldn't this happen by default??

**Comment by phimage** [comment]
The variable is set to `true` when token is filled
```swift
self.client.credential.oauth_token = accessToken
self.client.credential.oauth2 = true
success(credential: self.client.credential, response: response, parameters: responseParameters)
```

Are you talking about a scenario where you fill manually an old token?
In this case, you must set to `true` the `oauth2` variable ;(

If not how you achieve this?

**Comment by twistify** [comment]
`self.client.credential.oauth2` only gets set to `true` via a call to `postOAuthAccessTokenWithRequestTokenByCode` if `responseParameters["code"]` exists.  If you are authorising via OAuth2 and `responseParameters["access_token"]` exists but `responseParameters["code"]` doesn't, then `self.client.credential.oauth2` does not get set and defaults to `false`

```
            if let accessToken = responseParameters["access_token"] {
                self.client.credential.oauth_token = accessToken
                success(credential: self.client.credential, response: nil, parameters: responseParameters)
            }
            if let code = responseParameters["code"] {
                self.postOAuthAccessTokenWithRequestTokenByCode(code.stringByRemovingPercentEncoding!,
                    callbackURL:callbackURL,
                    success: { credential, response, responseParameters in
                        success(credential: credential, response: response, parameters: responseParameters)
                }, failure: failure)
            }
```

**Comment by phimage** [comment]
good point
so setting the oauth2 variable to true for that case solve this issue :8ball: 

```swift
 if let accessToken = responseParameters["access_token"] {
                self.client.credential.oauth_token = accessToken
                self.client.credential.oauth2 = true
                success(credential: self.client.credential, response: nil, parameters: responseParameters)
 }
 if let code = responseParameters["code"] {
```

You can make a PR or I will do it later
